{"uuid":"b9959405-929e-4b9a-a2aa-4c5cccb0c74d","historyId":"1e4324b702b3bfbb6f4371a71b21dd0a","fullName":"tests.authen.LoginTestWithDataProvider.TestLogin","labels":[{"name":"package","value":"tests.authen.LoginTestWithDataProvider"},{"name":"testClass","value":"tests.authen.LoginTestWithDataProvider"},{"name":"testMethod","value":"TestLogin"},{"name":"parentSuite","value":"Regression"},{"name":"suite","value":"MJSKLVNJAUDEPRV8"},{"name":"subSuite","value":"tests.authen.LoginTestWithDataProvider"},{"name":"host","value":"MBP-0196s-MacBook-Pro.local"},{"name":"thread","value":"3467@MBP-0196s-MacBook-Pro.local.TestNG-tests-2(16)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"TestLogin","status":"skipped","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"java.lang.RuntimeException: [ERR] Could not locate the found /Volumes/Data/Appium/SDETPRO_K11_MOBILE/main/java/tests/gson/login.json","trace":"java.lang.RuntimeException: java.lang.RuntimeException: [ERR] Could not locate the found /Volumes/Data/Appium/SDETPRO_K11_MOBILE/main/java/tests/gson/login.json\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:57)\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:157)\n\tat org.testng.internal.Parameters.handleParameters(Parameters.java:791)\n\tat org.testng.internal.Parameters.handleParameters(Parameters.java:728)\n\tat org.testng.internal.invokers.ParameterHandler.handleParameters(ParameterHandler.java:72)\n\tat org.testng.internal.invokers.ParameterHandler.createParameters(ParameterHandler.java:51)\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:917)\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1541)\n\tat org.testng.TestRunner.privateRun(TestRunner.java:806)\n\tat org.testng.TestRunner.run(TestRunner.java:601)\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:433)\n\tat org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:471)\n\tat org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base/java.lang.Thread.run(Thread.java:834)\nCaused by: java.lang.RuntimeException: [ERR] Could not locate the found /Volumes/Data/Appium/SDETPRO_K11_MOBILE/main/java/tests/gson/login.json\n\tat test_data.utils.DataObjectBuilder.buildDataObject(DataObjectBuilder.java:23)\n\tat tests.authen.LoginTestWithDataProvider.loginCredDataSet(LoginTestWithDataProvider.java:36)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:566)\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:53)\n\t... 19 more\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[{"name":"udid","value":"MJSKLVNJAUDEPRV8"},{"name":"platformName","value":"android"},{"name":"platformVersion","value":"15.0"},{"name":"systemPort","value":"8536"}],"start":1670120145567,"stop":1670120145568}